// League and team catalog (Fictionalized for licensing)

export const LEAGUES = {
    epl: { id: 'epl', name: 'Premier Division' },
    laliga: { id: 'laliga', name: 'Primera League' },
    seriea: { id: 'seriea', name: 'Italian A League' },
    bundesliga: { id: 'bundesliga', name: 'German Masters' },
    ligue1: { id: 'ligue1', name: 'French Elite' },
    cyprus: { id: 'cyprus', name: 'Cypriot Top Flight' },
    greece: { id: 'greece', name: 'Greek Super League' },
    iran: { id: 'iran', name: 'Persian Gulf Pro League' }
};

export const TEAMS = [
    // Premier Division (20 teams)
    { id: 'asr', name: 'Highbury Gunners', leagueId: 'epl' },
    { id: 'avl', name: 'Villa Lions', leagueId: 'epl' },
    { id: 'bou', name: 'Bournemouth Cherries', leagueId: 'epl' },
    { id: 'bfo', name: 'Brentford Bees', leagueId: 'epl' },
    { id: 'bha', name: 'Brighton Bees', leagueId: 'epl' },
    { id: 'che', name: 'The Blues FC', leagueId: 'epl' },
    { id: 'cry', name: 'Crystal Eagles', leagueId: 'epl' },
    { id: 'eve', name: 'Palace Glaziers', leagueId: 'epl' },
    { id: 'ful', name: 'Fulham Cottagers', leagueId: 'epl' },
    { id: 'ips', name: 'Hampton Town', leagueId: 'epl' },
    { id: 'lei', name: 'Leicester Foxes', leagueId: 'epl' },
    { id: 'liv', name: 'Anfield Reds', leagueId: 'epl' },
    { id: 'mci', name: 'Azure Sky FC', leagueId: 'epl' },
    { id: 'mun', name: 'Red Devils', leagueId: 'epl' },
    { id: 'new', name: 'Newcastle Magpies', leagueId: 'epl' },
    { id: 'nfo', name: 'Nottingham Woods', leagueId: 'epl' },
    { id: 'sou', name: 'Southampton Saints', leagueId: 'epl' },
    { id: 'tot', name: 'Tyneside Magpies', leagueId: 'epl' },
    { id: 'whu', name: 'East London Irons', leagueId: 'epl' },
    { id: 'wol', name: 'London Hammers', leagueId: 'epl' },

    // Primera League (20 teams)
    { id: 'ala', name: 'Basque Glorious', leagueId: 'laliga' },
    { id: 'alm', name: 'Almeria Royals', leagueId: 'laliga' },
    { id: 'ath', name: 'Bilbao Lions', leagueId: 'laliga' },
    { id: 'atm', name: 'Madrid Stripes', leagueId: 'laliga' },
    { id: 'bar', name: 'Catalan Giants', leagueId: 'laliga' },
    { id: 'bet', name: 'Seville Greens', leagueId: 'laliga' },
    { id: 'cad', name: 'Andalusian Yellows', leagueId: 'laliga' },
    { id: 'cel', name: 'Vigo Celts', leagueId: 'laliga' },
    { id: 'get', name: 'Getafe Blues', leagueId: 'laliga' },
    { id: 'gir', name: 'Catalan Whites', leagueId: 'laliga' },
    { id: 'gra', name: 'Granada Reds', leagueId: 'laliga' },
    { id: 'las', name: 'Canary Islanders', leagueId: 'laliga' },
    { id: 'mal', name: 'Mallorca Yellows', leagueId: 'laliga' },
    { id: 'osa', name: 'Pamplona Reds', leagueId: 'laliga' },
    { id: 'ray', name: 'Vallecas Stripes', leagueId: 'laliga' },
    { id: 'rma', name: 'Royal Whites', leagueId: 'laliga' },
    { id: 'rso', name: 'San Sebastian Royals', leagueId: 'laliga' },
    { id: 'sev', name: 'Seville Fliers', leagueId: 'laliga' },
    { id: 'val', name: 'Valencia Bats', leagueId: 'laliga' },
    { id: 'vil', name: 'Villarreal Yellows', leagueId: 'laliga' },

    // Italian A League (20 teams)
    { id: 'ata', name: 'Bergamo Goddess', leagueId: 'seriea' },
    { id: 'bol', name: 'Bologna Greyhounds', leagueId: 'seriea' },
    { id: 'cag', name: 'Cagliari Islanders', leagueId: 'seriea' },
    { id: 'emp', name: 'Empoli Blues', leagueId: 'seriea' },
    { id: 'fio', name: 'Florence Violets', leagueId: 'seriea' },
    { id: 'fro', name: 'Frosinone Lions', leagueId: 'seriea' },
    { id: 'gen', name: 'Genoa Griffins', leagueId: 'seriea' },
    { id: 'hel', name: 'Verona Yellow-Blues', leagueId: 'seriea' },
    { id: 'int', name: 'Milan Nerazzurri', leagueId: 'seriea' },
    { id: 'juv', name: 'Turin Zebras', leagueId: 'seriea' },
    { id: 'laz', name: 'Rome Eagles', leagueId: 'seriea' },
    { id: 'lec', name: 'Lecce Wolves', leagueId: 'seriea' },
    { id: 'mil', name: 'Rossoneri Devils', leagueId: 'seriea' },
    { id: 'mon', name: 'Monza Whites', leagueId: 'seriea' },
    { id: 'nap', name: 'Rome Light Blues', leagueId: 'seriea' },
    { id: 'rom', name: 'Rome Gladiators', leagueId: 'seriea' },
    { id: 'sal', name: 'Salerno Garnets', leagueId: 'seriea' },
    { id: 'sas', name: 'Salerno Seahorses', leagueId: 'seriea' },
    { id: 'tor', name: 'Turin Bulls', leagueId: 'seriea' },
    { id: 'udi', name: 'Udinese Zebras', leagueId: 'seriea' },

    // German Masters (18 teams)
    { id: 'aug', name: 'Augsburg Fuggers', leagueId: 'bundesliga' },
    { id: 'b04', name: 'Rhine Lions', leagueId: 'bundesliga' },
    { id: 'bay', name: 'Bavarian Reds', leagueId: 'bundesliga' },
    { id: 'boc', name: 'Augsburg Fuggers', leagueId: 'bundesliga' },
    { id: 'bvb', name: 'Black Yellows', leagueId: 'bundesliga' },
    { id: 'bmg', name: 'Monchengladbach Foals', leagueId: 'bundesliga' },
    { id: 'col', name: 'Cologne Billy Goats', leagueId: 'bundesliga' },
    { id: 'dar', name: 'Darmstadt Lilies', leagueId: 'bundesliga' },
    { id: 'ein', name: 'Frankfurt Eagles', leagueId: 'bundesliga' },
    { id: 'fre', name: 'Freiburg Breisgau', leagueId: 'bundesliga' },
    { id: 'hei', name: 'Heidenheim Griffins', leagueId: 'bundesliga' },
    { id: 'hof', name: 'Hoffenheim Blues', leagueId: 'bundesliga' },
    { id: 'lei', name: 'Leipzig Bulls', leagueId: 'bundesliga' },
    { id: 'm05', name: 'Mainz Carnivals', leagueId: 'bundesliga' },
    { id: 'stu', name: 'Stuttgart Swabians', leagueId: 'bundesliga' },
    { id: 'svw', name: 'Werder Rivermen', leagueId: 'bundesliga' },
    { id: 'uni', name: 'Union Berliners', leagueId: 'bundesliga' },
    { id: 'vfl', name: 'Bochum Blues', leagueId: 'bundesliga' },

    // French Elite (18 teams)
    { id: 'cle', name: 'Brest Pirates', leagueId: 'ligue1' },
    { id: 'fcl', name: 'Clermont Lancers', leagueId: 'ligue1' },
    { id: 'hav', name: 'Le Havre Blues', leagueId: 'ligue1' },
    { id: 'len', name: 'Lens Blood & Gold', leagueId: 'ligue1' },
    { id: 'lil', name: 'Lille Mastiffs', leagueId: 'ligue1' },
    { id: 'lor', name: 'Lorient Merluccius', leagueId: 'ligue1' },
    { id: 'lyo', name: 'Rhone Lads', leagueId: 'ligue1' },
    { id: 'mar', name: 'Phocaean Olympians', leagueId: 'ligue1' },
    { id: 'met', name: 'Metz Maroons', leagueId: 'ligue1' },
    { id: 'mon', name: 'Monaco Princes', leagueId: 'ligue1' },
    { id: 'mhp', name: 'Montpellier Heralds', leagueId: 'ligue1' },
    { id: 'nan', name: 'Nantes Canaries', leagueId: 'ligue1' },
    { id: 'nic', name: 'Nice Eagles', leagueId: 'ligue1' },
    { id: 'psg', name: 'Paris Princes', leagueId: 'ligue1' },
    { id: 'rei', name: 'Reims Red & Whites', leagueId: 'ligue1' },
    { id: 'ren', name: 'Rennes Red Blacks', leagueId: 'ligue1' },
    { id: 'str', name: 'Strasbourg Racers', leagueId: 'ligue1' },
    { id: 'tou', name: 'Toulouse Violets', leagueId: 'ligue1' },

    // Cypriot Top Flight (14 teams)
    { id: 'aek', name: 'Larnaca Guardians', leagueId: 'cyprus' },
    { id: 'ael', name: 'Larnaca Yellows', leagueId: 'cyprus' },
    { id: 'ano', name: 'Famagusta Blues', leagueId: 'cyprus' },
    { id: 'apo', name: 'Nicosia Legends', leagueId: 'cyprus' },
    { id: 'apollon', name: 'Limassol Gods', leagueId: 'cyprus' },
    { id: 'ari', name: 'Light Brigade', leagueId: 'cyprus' },
    { id: 'dox', name: 'Katokopia Greens', leagueId: 'cyprus' },
    { id: 'eth', name: 'Achnas Blues', leagueId: 'cyprus' },
    { id: 'kar', name: 'Polemidia Reds', leagueId: 'cyprus' },
    { id: 'nea', name: 'Salamis Reds', leagueId: 'cyprus' },
    { id: 'omo', name: 'Green Shamrocks', leagueId: 'cyprus' },
    { id: 'paf', name: 'Paphos Coastal', leagueId: 'cyprus' },
    { id: 'zak', name: 'Zakakiou Lions', leagueId: 'cyprus' },
    { id: 'karm', name: 'Pano Reds', leagueId: 'cyprus' },

    // Greek Super League (14 teams)
    { id: 'aekg', name: 'Athens double-headed Eagles', leagueId: 'greece' },
    { id: 'arisg', name: 'Thessaloniki Gods of War', leagueId: 'greece' },
    { id: 'aste', name: 'Tripolis Stars', leagueId: 'greece' },
    { id: 'atro', name: 'Tripoli Fearless', leagueId: 'greece' },
    { id: 'kifi', name: 'Athens Blue-Whites', leagueId: 'greece' },
    { id: 'lamia', name: 'Phthiotis Blues', leagueId: 'greece' },
    { id: 'ofic', name: 'Crete Snakes', leagueId: 'greece' },
    { id: 'olymp', name: 'Piraeus Legends', leagueId: 'greece' },
    { id: 'panat', name: 'Athens Shamrocks', leagueId: 'greece' },
    { id: 'panet', name: 'Agrinio Canaries', leagueId: 'greece' },
    { id: 'pans', name: 'Serres Lions', leagueId: 'greece' },
    { id: 'paok', name: 'Thessaloniki Eagles', leagueId: 'greece' },
    { id: 'pasg', name: 'Epirus Bull', leagueId: 'greece' },
    { id: 'volos', name: 'Thessaly Reds', leagueId: 'greece' },

    // Persian Gulf Pro League (16 teams)
    { id: 'alum', name: 'Arak Green-Whites', leagueId: 'iran' },
    { id: 'este', name: 'Tehran Blues', leagueId: 'iran' },
    { id: 'estk', name: 'Khuzestan Blues', leagueId: 'iran' },
    { id: 'fool', name: 'Ahvaz Steel', leagueId: 'iran' },
    { id: 'golg', name: 'Sirjan Miners', leagueId: 'iran' },
    { id: 'hava', name: 'Tehran Aviators', leagueId: 'iran' },
    { id: 'male', name: 'Anzali Sailors', leagueId: 'iran' },
    { id: 'mesr', name: 'Rafsanjan Coppers', leagueId: 'iran' },
    { id: 'nass', name: 'Mazandaran Tigers', leagueId: 'iran' },
    { id: 'payk', name: 'Tehran Automakers', leagueId: 'iran' },
    { id: 'pers', name: 'Tehran Reds', leagueId: 'iran' },
    { id: 'sana', name: 'Abadan Brazilians', leagueId: 'iran' },
    { id: 'sepa', name: 'Isfahan Golden Boys', leagueId: 'iran' },
    { id: 'sham', name: 'Qazvin Greens', leagueId: 'iran' },
    { id: 'trac', name: 'Isfahan Yellows', leagueId: 'iran' },
    { id: 'zoba', name: 'Isfahan Lions', leagueId: 'iran' }
];

export function getTeamsByLeague(leagueId) {
    return TEAMS.filter(t => t.leagueId === leagueId);
}
